server:
  port: 8189
  servlet:
    context-path: /testcase1

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#  datasource:
#    url: jdbc:mysql://localhost:3306/
#    username:
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL80Dialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update